seml:
  executable: examples/tutorial/example_experiment.py
  name: example_experiment
  output_dir: examples/logs
  project_root_dir: ../..

slurm:
  experiments_per_job: 1
  sbatch_options:
    gres: gpu:1       # num GPUs
    mem: 16G          # memory
    cpus-per-task: 2  # num cores
    time: 0-08:00     # max time, D-HH:MM

grid:
  learning_rate:
    type: choice
    options:
      - 1
      - 2
      - 3
    group: 'test'

  max_epochs:
    type: choice
    options:
      - 10
      - 20
      - 30
    group: 'test'
    
  test.test2:
    type: choice
    options:
      - 100
      - 200
      - 300

small_datasets:
  fixed:
    hidden_sizes: [32, 16] # this will be parsed into a Python list.

large_datasets:

  fixed:
    hidden_sizes: [128, 64, 32]
